# Mihomo external controller URL, Required
mihomo-api: http://127.0.0.1:9093

# Mihomo external controller secret, Optional
#mihomo-secret:

# Path to mihomo config JSON schema file, Optional, default is builtin core-config.schema.json
#mihomo-config-schema:

# Log file, Optional, write log only if exists, linux example: /tmp/mihomo-tui.log
log-file: mihomo-tui.log

# Log level(silent/trace/debug/info/warning/error), Optional, default is error.
# Examples:
#   error
#   info,mihomo_tui=debug
#   info,mihomo_tui=trace,mihomo_tui::app=debug
log-level: error
